### ISSUE TITLE
Updates to Development Guide for Windows

### ISSUE THREAD

**Issue by ssc9309** [lulzsun/RePlays#104]
"Build should be successful if the file `~\obs-studio-build\build\win64\bin\64bit\obs.dll` exists"

I think the path needs to be changed to 

`~\obs-studio-build\obs-studio-release\bin\64bit`

**Comment by lulzsun** [comment]
Thanks! The build script was modified awhile ago and the development guide was not updated to reflect the changes.

It has been corrected.

**Comment by ssc9309** [comment]
Uh. I think I was too quick with this one. Still having the obs.dll issues. Investigation continues...

**Comment by ssc9309** [comment]
Is there supposed to be any manual copying required if I follow the build-libobs.cmd method?

**Comment by lulzsun** [comment]
Everything should be automated. It is possible that you are running into an error while running the cmd script, because the script will not prompt an error and will close immediately after any situation it runs into.

You could try opening up a new command prompt and opening the script through there so that way the prompt doesn't immediately close so you can scroll through the prompt and look for possible issues.

If I were to guess the issue, you might not have `cmake` accessible (needs to be manually set in system environment variables) and possibly with the other requirements such as `git` and `7zip`.

**Comment by ssc9309** [comment]
I investigated into the build script and applied this solution. https://stackoverflow.com/questions/51668676/cmake-visual-studio-15-2017-could-not-find-any-instance-of-visual-studio

It now looks like the obs built script ran successfully.

When trying to run debug afterwards though, it's still stuck at
`if (obs_initialized()) {`
saying unable to load obs.dll

Looking at the obs build script. It doesn't seem to have any copy to debug directory. Am I going in the right direction to resolve this?

**Comment by lulzsun** [comment]
You are correct in that the obs build script does not copy to the debug directory. In fact that is the job of the [C# project file](https://github.com/lulzsun/RePlays/blob/main/RePlays.csproj#L83-L89) when you start debugging. If `~\obs-studio-build\build\win64\bin\64bit\obs.dll` did not exist, it would throw an error immediately upon debugging.

Since you were able to start debugging but are getting runtime error tells me that the obs build was only partially successful since there was an issue loading the obs.dll file. You can try to double-check and see if the obs.dll file exists in the debug directory. 

I am unsure what else could be causing the issue, you may have to look through the output of the build script to see if there are any abnormalities

**Comment by ssc9309** [comment]
Ok. All problems resolved!
- completely blew out the repo
- fresh cloned the repo
- ran the build obs command
- opened sln
- ran debug.

The problem must have been that the first faulty run of the build command must have left some residual problems. Maybe it could have been solved if I deleted the obs-studio-build folder?
