### ISSUE TITLE
Display capture doesn't work

### ISSUE THREAD

**Issue by Segergren** [lulzsun/RePlays#174]
I've got a problem with the `GetMonitorId` function since the change made 43 days ago. When I try to get the ID for \\.\DISPLAY1 using `GetMonitorInfo(hMonitor, ref monitorInfo)`, it doesn't work – it just returns `false`. There are no error messages to help me figure out why.

Because of this, my screen recording isn't working right – it just shows a black screen. 

```
[1/19/2024 9:15:00 PM][LibObsRecorder.cs::StartRecording(375)]: Attempting to use display capture instead
[1/19/2024 9:15:00 PM][WindowService.cs::GetMonitorId(567)]: Attempting to retrieve deviceId from \\.\DISPLAY1
[1/19/2024 9:15:00 PM][WindowService.cs::GetMonitorId(589)]: Could not retrieve deviceId for \\.\DISPLAY1
[1/19/2024 9:15:00 PM][LibObsRecorder.cs::Start(107)]: info: [duplicator-monitor-capture: 'display'] update settings:
	display:  (0x0)
	cursor: true
	method: WGC
	id: 
	alt_id: 
	setting_id: DUMMY
	force SDR: false
[1/19/2024 9:15:00 PM][LibObsRecorder.cs::Start(107)]: debug: source 'display' (monitor_capture) created
```

**Comment by lulzsun** [comment]
Should be fixed in 33bad6f, let me know if there are still issues.

**Comment by Segergren** [comment]
I'm sadly still having issues.
Looks like it actually gets the ID but is instead having issues with 
`device_duplicator_create: Failed to DuplicateOutput1 (887A0004)`

It just spams this log message every third second until the recording is stopped. 
I think the error comes from this file: https://github.com/obsproject/obs-studio/blob/master/libobs-d3d11/d3d11-duplicator.cpp
[1.2.63.txt](https://github.com/lulzsun/RePlays/files/14228989/1.2.63.txt)

**Comment by lulzsun** [comment]
Fixed by https://github.com/lulzsun/RePlays/commit/5aa43cb7b3e566ef7834a2dd823e81f8878adc46. Closing issue.
